### ISSUE TITLE
Not all inputs are available

### ISSUE THREAD

**Issue by jack-blackson** [ACDR/homebridge-yamaha-avr#19]
Hey!

I installed the homebridge yamaha plugin to use it with my Yamaha RX-V473 receiver. The main purpose was to start the radio with siri. 

The connection to the receiver is working, but I am wondering why I don't get the source "tuner" as available input. I have this setup:

<img width="258" alt="grafik" src="https://user-images.githubusercontent.com/13975634/82756994-eb587e80-9ddd-11ea-9643-8cdbb54793f7.png">

With that, as far as I could read, all available inputs should be displayed, but I just get these:

- V-AUX
- HDMI 1-4
- USB
- AV 1-6

Is there anything I am doing wrong?

Thanks,
Jack

**Comment by slydlake** [comment]
look at #22

**Comment by okpop** [comment]
Hi I'm actually having the same issue and did look at #22.  There seems to be some issues whit how a few inputs are still being handled.

For starters, I would like to have only my used or "favorite" inputs show up so I would like to include in my config file            ```
_"inputs": [
                {
                    "id": "AV5",
                    "name": "Nindendo Wii"
                },
                {
                    "id": "HDMI1",
                    "name": "Playstation 3"
                },
                {
                    "id": "HDMI2",
                    "name": "Raspbery Pi 4"
                },
                {
                    "id": "HDMI3",
                    "name": "Playstation 3"
                },
                {
                    "id": "HDMI4",
                    "name": "HTPC"
                },
                {
                    "id": "HDMI5",
                    "name": "Apple TV 4K"
                },
                {
                    "id": "Spotify",
                    "name": "Spotify"
                },
                {
                    "id": "AirPlay",
                    "name": "AirPlay"
                },
                {
                    "id": "PHONO",
                    "name": "Phono"
                },
                {
                    "id": "BLUETOOTH",
                    "name": "Bluetooth"
                },
                {
                    "id": "USB",
                    "name": "USB"
                },
                {
                    "id": "V-AUX",
                    "name": "V-AUX"
                }
            ]_
```

This results in Tuner not showing up in the list of available inputs and start to get into problems if I have selected it from the receiver.  All inputs including Spotify and V-AUX do work this way just, not the Tuner.

If I don't include the above in the config file and let @slydlake's update do its thing I do get back a correct list of all inputs for my receiver, however, Tuner and V-AUX do not change inputs to anything rather the input remains.  You do see the call in the logs for Homebridge but you see immediately that the input gets updated right back to what it is since the receiver never changed.

I would love to know how to include Tuner in my list of "favorite" inputs so I don't also have to scroll through inputs like my AV- to 4 that I don't use or all of the other streaming services I have no use for.

So far this is one of the better AVR implementations I've played with ut would be great to figure out those last inputs.

Thoughts?

**Comment by okpop** [comment]
After thinking about this a bit more.  I think the problem (for me at least) is with the sanitization of the inputs.  V-AUX has a - and I believe that TUNER actually should be returning an input state that might include "PRESET FM:01" for example or some other return with a special char in it.

Beyond this bit of info, I'm not sure exactly how to fix this though.

**Comment by ACDR** [comment]
@okpop - this should be fixed in the beta release:
https://github.com/ACDR/homebridge-yamaha-avr/releases/tag/v2.0.0-beta.1

`npm install -g homebridge-yamaha-avr@beta`

Please give that a shot and let me know if the issue persists.
