### ISSUE TITLE
Plugin is blocking other plugins

### ISSUE THREAD

**Issue by clemi2408** [ACDR/homebridge-yamaha-avr#21]
If i setup the AVR in config.json - buttons in Home app are working and everything is fine.

If i take the avr device offline, and the yamaha plugin cant reach the device, all other homebridge plugins are blocked and the app shows the status „not available“

**Comment by slydlake** [comment]
I have this problem too
I could solve the problem when I switch the input from Spotify to another input (HDMI1). After that everything works fine.

I have no inputs defined in the config.json. But Spotify will not show as an input.

So I think the problem is that Spotify is not recognized as Input.
Could you solve this Spotify problem?

**Comment by slydlake** [comment]
Solution is on the pull request: https://github.com/ACDR/homebridge-yamaha-avr/pull/22
or just use the code from my forked repository
